export const COURSE_DETAIL_TRIAL_REQUEST = "COURSE_DETAIL_TRIAL_REQUEST";
export const COURSE_DETAIL_TRIAL_SUCCESS = "COURSE_DETAIL_TRIAL_SUCCESS";
export const COURSE_DETAIL_TRIAL_FAIL = "COURSE_DETAIL_TRIAL_FAIL";
